### ISSUE TITLE
Atom v1.12 crashing when opened in dev-mode

### ISSUE THREAD

**Issue by Alhadis** [nwhetsell/language-csound#1]
After upgrading to Atom v1.12, I noticed the editor crashing every time I opened a window in dev-mode. I [originally believed it](https://github.com/atom/atom/issues/13171) to be a bug in Atom's core, but the crashing stopped after disabling this package.

The solution seems to be to simply run `apm rebuild` and/or `apm install` in the installed package's directory, which suggests the [package's dependencies](https://github.com/nwhetsell/language-csound/blob/master/package.json#L17-L20) are the issue. I'm not sure why they would only pose an issue in dev-mode, however.

Out of curiosity, is there any reason they're not listed as `devDependencies` instead?

**Comment by Alhadis** [comment]
I noticed the package is still failing to load, even after running `apm install && apm rebuild`:

<img src="https://cloud.githubusercontent.com/assets/2346707/20208750/53521444-a844-11e6-88c9-6da38a0aa5e0.png" width="576" alt="Figure 1" />

@nwhetsell I'm not sure [what this code is doing](https://github.com/nwhetsell/language-csound/blob/master/lib/language-csound.coffee#L15-L23), or why it's necessary, but I'm sure there're plenty of ways to achieve what you're doing without having a hard dependency on `first-mate`. Recall that `first-mate` has dependencies on other modules that require native recompilation (for the Oniguruma engine), which is what's introducing these complications.

**Comment by nwhetsell** [comment]
Weird; I upgraded to Atom v1.12.1 before this came in, so I can’t install language-csound and then see what happens with `apm install && apm rebuild`, unfortunately. For what it’s worth, I just opened [this file](https://github.com/github/linguist/blob/master/samples/Csound/test.orc) in dev mode without incident.

Commit 38c17399 eliminated the need for [season](https://www.npmjs.com/package/season), and I’ll remove that from the list of dependencies.

I’m [subclassing](https://github.com/nwhetsell/language-csound/blob/master/lib/csound-pattern.coffee#L6) first-mate’s Pattern class to handle a peculiarity of Csound (the first one or two characters of variable names are type sigils), so I actually need first-mate somewhere, but for some unknown reason I was under the impression that having first-mate in the list of dependencies would only install it if Atom’s built-in first-mate was somehow not there. I think it’s safe to assume that Atom will use first-mate for the foreseeable future, so I’ll remove that too.

**Comment by nwhetsell** [comment]
This package now has no dependencies (commits 1d40a1433534d41b53d63f8ea52b2979e624cd62 and 1579063629a27448aebd8564cdadeca1643862e4), and I just published these changes. Can you update this package and see if dev mode now works?

**Comment by Alhadis** [comment]
Sorry, still [recovering from package loss](https://github.com/atom/apm/issues/460). I reinstalled `language-csound` and can confirm that dev-mode works correctly. 👍

Might be the time to point out a deprecation error that's been picked up when running in dev-mode, too:

-------------
> **TextEditor.get is deprecated.**
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:100:14)
<unknown> (/Users/johngardner/.atom/packages/language-csound/lib/csound-pattern.coffee:33:33)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:679:20)
TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:12)
```

**Comment by nwhetsell** [comment]
Excellent!

Thanks for these issue reports; I’ve removed uses of `DisplayBuffer` in commit 4ef64cd1d1431bfa9ced2fc84343373c93016bef.

**Comment by Alhadis** [comment]
Ace, thanks mate.
